services:
  backend:
    build:
      context: ./backend
      target: deps
    command: yarn dev
    container_name: be-the-hero_backend
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: be_the_hero
      DATABASE_PASSWORD: secret
      DATABASE_USER: docker
    ports:
      - 3333:3333
    volumes:
      - ./backend/:/app/
      - /app/node_modules/

  frontend:
    build:
      context: ./frontend
      target: deps
    command: pnpm dev
    container_name: be-the-hero_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3333
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend/:/app/
      - /app/node_modules/

  postgres:
    container_name: be-the-hero_postgres
    environment:
      POSTGRES_DB: be_the_hero
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
    image: postgres:14-alpine
    ports:
      - 5432:5432
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: be-the-hero_pgadmin
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    image: dpage/pgadmin4
    ports:
      - 8080:80
    tty: true

volumes:
  postgres_data:
