version: "3.9"

services:
  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    container_name: be-the-hero_api
    depends_on:
      - postgres
    ports:
      - 3333:3333
    restart: unless-stopped
    volumes:
      - ./packages/api/:/app/
      - /app/node_modules/

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    container_name: be-the-hero_web
    ports:
      - 3000:3000
    restart: unless-stopped
    stdin_open: true
    volumes:
      - ./packages/web/:/app/
      - /app/node_modules/

  postgres:
    container_name: be-the-hero_postgres
    environment:
      POSTGRES_DB: be_the_hero
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
    image: postgres:13-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: be-the-hero_pgadmin
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    image: dpage/pgadmin4
    ports:
      - 8080:80
    tty: true

volumes:
  postgres_data: