name: API CI

on:
  push:
    branches: [ master ]
    paths:
    - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'api/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build --if-present
    - run: yarn test
