name: API CI

on:
  push:
    branches: [ master ]
    paths:
    - 'packages/api/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'packages/api/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04
    
    env:
      working-directory: packages/api

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: yarn test
      working-directory: ${{env.working-directory}}
